name: Deploy to GitHub Pages

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: windows-latest
    steps:
      - uses: GuillaumeFalourd/setup-rsync@v1.1
      - run: rsync --version
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 7.0.x

      - name: Build and Publish
        run: |
          dotnet publish -c Release -o publish
          # Additional build and packaging steps as needed

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          ACCESS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: IQDeployment
          FOLDER: ./publish  # Specify the folder containing your app's output

